<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Lumio.Server.Account</RootNamespace>
    <AssemblyName>Lumio.Server.Account</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="Isopoh.Cryptography.Argon2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lumio.Server.Account.Tests" />
    <InternalsVisibleTo Include="lumio-account-server" />
  </ItemGroup>

</Project>
