<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Lumio.Server.Account.App</RootNamespace>
    <AssemblyName>lumio-account-server</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lumio.Server.Account.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Lumio.Server.Account/Lumio.Server.Account.csproj" />
  </ItemGroup>

</Project>
